WIP Add hosted zone sanity check in init script
kubefirst/nebulous pull request #4
Opened 2021-04-29 21:52 UTC by tjengland

2021-05-04 02:00 UTC, johndietz requested changes
@tjengland thanks for your open source contribution. just 2 small edits needed when you have a moment to take look.

2021-05-04 16:00 UTC, tjengland commented on scripts/nebulous/init.sh
> +HZ_LIVENESS_FAIL_COUNT=0
moved this to docker file after experiencing weird issues with nslookup, lmk if you prefer to leave it in the init script itself

2021-05-04 16:00 UTC, tjengland commented on scripts/nebulous/init.sh
> +HZ_LIVENESS_URL=livenesstest.$HOSTED_ZONE_NAME.com
removed

2021-05-08 15:34 UTC, johndietz approved these changes
negative and positive testing were both completed successfully. approved for merge. great work @tjengland - thanks for the oss contribution.

2021-05-08 15:35 UTC, merged